/*
 
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1
 
 File: ZGARENTA_EKHIZMET_SRVServiceV0.h
 Abstract: The generated proxy classes for the ZGARENTA_EKHIZMET_SRV Service.   
*/

#import <Foundation/Foundation.h>
#import "BaseEntityType.h"
#import "BaseComplexType.h"
#import "BaseServiceObject.h"

#pragma mark - Complex Types



#pragma mark - Entity Types

/**
 Each of the following classes represents an entity-type of the ZGARENTA_EKHIZMET_SRVServiceV0 service.
 
 Any entity-type class should be used as following:
 
 1. The entity object may represent an existing entry of an appropriate service collection,
 if the object is initialized using data returned from an appropriate service call.
 This may be achieved by using the initWithSDMEntry: constructor,
 or using the static methods creating the entity object (parse<entity-type-name>EntriesWithData,
 parse<entity-type-name>EntryWithData, and create<entity-type-name>EntriesForSDMEntries).
 
 For retrieving the entry data, use the appropriate query properties and methods of this class 
 and of the ZGARENTA_EKHIZMET_SRVServiceV0 class, and then execute the request (see the SDMConnectivityHelper class).
 
 2. Another option is to use this entity object as a new entry to create in an appropriate service collection.
 In this case, use the init constructor and set the appropriate properties. 
 Note that some features (as navigation properties) are not available in this mode (since it is not yet an actual service entry).
 Use the SDMConnectivityHelper class and the getXMLForCreateRequest method of the BaseServiceObject class, to send the 'create' request.
 Then use the service response for constructing a new object, in order to represent the entry as existed in the service. 
 
 In both operation modes, setting the entity property values will not affect the service until the changes are sent to the server.
 For sending changes to the server, see the SDMConnectivityHelper class and the getXMLForRequest methods of the BaseServiceObject class.
 It is recommended to use the server response for constructing a new object, in order to represent the entry as existed in the service.
 
 Note: For proper behavior of this class, make sure to initialize the ZGARENTA_EKHIZMET_SRVServiceV0 class
 in your application, before initializing the entity-type class objects.
*/
 

#pragma mark - AdditionalEquipmentServiceV0
@interface AdditionalEquipmentServiceV0 : BaseEntityType 

@property (strong, nonatomic) NSDate *ImppBegda; ///< Start Date - Edm.DateTime
@property (strong, nonatomic) NSString *ImppBeguz; ///< Character Field Length = 10 - Edm.String
@property (strong, nonatomic) NSString *ImppDsube; ///< IMPP_DSUBE - Edm.String
@property (strong, nonatomic) NSDate *ImppEndda; ///< End Date - Edm.DateTime
@property (strong, nonatomic) NSString *ImppEnduz; ///< Character Field Length = 10 - Edm.String
@property (strong, nonatomic) NSString *ImppFikod; ///< IMPP_FIKOD - Edm.String
@property (strong, nonatomic) NSString *ImppGrpkod; ///< IMPP_GRPKOD - Edm.String
@property (strong, nonatomic) NSString *ImppKampid; ///< Text 24 - Edm.String
@property (strong, nonatomic) NSString *ImppLangu; ///< Language Key of Text Environment - Edm.String
@property (strong, nonatomic) NSString *ImppMarkaid; ///< IMPP_MARKAID - Edm.String
@property (strong, nonatomic) NSString *ImppModelid; ///< IMPP_MODELID - Edm.String
@property (strong, nonatomic) NSString *ImppMsube; ///< Storage Location - Edm.String
@property (strong, nonatomic) NSString *ImppRezno; ///< Sales Document - Edm.String
@property (strong, nonatomic) NSString *ImppSozno; ///< Sales Document - Edm.String
#pragma mark Entity Navigation Properties
@property (strong, nonatomic) ODataQuery *EXPT_EKPLISTSetQuery;
@property (strong, nonatomic) NSMutableArray *EXPT_EKPLISTSet;
@property (strong, nonatomic) ODataQuery *EXPT_SIGORTASetQuery;
@property (strong, nonatomic) NSMutableArray *EXPT_SIGORTASet;
@property (strong, nonatomic) ODataQuery *EXPT_HIZMETSetQuery;
@property (strong, nonatomic) NSMutableArray *EXPT_HIZMETSet;
@property (strong, nonatomic) ODataQuery *EXPT_HASARSetQuery;
@property (strong, nonatomic) NSMutableArray *EXPT_HASARSet;
@property (strong, nonatomic) ODataQuery *EXPT_EKSURUCUSetQuery;
@property (strong, nonatomic) NSMutableArray *EXPT_EKSURUCUSet;

#pragma mark Static Methods
/**
 Static method that returns an array of AdditionalEquipmentServiceV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to AdditionalEquipmentServiceV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of AdditionalEquipmentServiceV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseAdditionalEquipmentServiceEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of AdditionalEquipmentServiceV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to AdditionalEquipmentServiceV0 entities.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of AdditionalEquipmentServiceV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedAdditionalEquipmentServiceEntriesWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single AdditionalEquipmentServiceV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a AdditionalEquipmentServiceV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a AdditionalEquipmentServiceV0 entity. Returns nil if the data in invalid.
*/
+ (AdditionalEquipmentServiceV0 *)parseAdditionalEquipmentServiceEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single AdditionalEquipmentServiceV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a AdditionalEquipmentServiceV0 entity.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a AdditionalEquipmentServiceV0 entity. Returns nil if the data in invalid.
*/
+ (AdditionalEquipmentServiceV0 *)parseExpandedAdditionalEquipmentServiceEntryWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of AdditionalEquipmentServiceV0 objects from a given array of ODataEntry objects.
 @param sdmEntries Array of ODataEntry objects.
 @return Array of AdditionalEquipmentServiceV0 objects.
*/
+ (NSMutableArray *)createAdditionalEquipmentServiceEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ZGARENTA_EKHIZMET_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(ODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ZGARENTA_EKHIZMET_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(ODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;


#pragma mark Entity Navigation Property loading methods
/**
 Navigation property. Loads EXPT_EKPLISTSet details for this entity from the provided data.
 @param aData The NSData containing the EXPT_EKPLISTSet information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadEXPT_EKPLISTSetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Navigation property. Loads EXPT_SIGORTASet details for this entity from the provided data.
 @param aData The NSData containing the EXPT_SIGORTASet information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadEXPT_SIGORTASetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Navigation property. Loads EXPT_HIZMETSet details for this entity from the provided data.
 @param aData The NSData containing the EXPT_HIZMETSet information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadEXPT_HIZMETSetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Navigation property. Loads EXPT_HASARSet details for this entity from the provided data.
 @param aData The NSData containing the EXPT_HASARSet information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadEXPT_HASARSetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Navigation property. Loads EXPT_EKSURUCUSet details for this entity from the provided data.
 @param aData The NSData containing the EXPT_EKSURUCUSet information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadEXPT_EKSURUCUSetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


@end

#pragma mark - EXPT_EKPLISTV0
@interface EXPT_EKPLISTV0 : BaseEntityType 

@property (strong, nonatomic) NSString *Msube; ///< Storage Location - Edm.String
@property (strong, nonatomic) NSString *Matnr; ///< Material - Edm.String
@property (strong, nonatomic) NSString *MusTanimi; ///< Char - Edm.String
@property (strong, nonatomic) NSString *Zorunlu; ///< ZORUNLU - Edm.String
@property (strong, nonatomic) NSDecimalNumber *MaxMiktar; ///< Quantity - Edm.Decimal
@property (strong, nonatomic) NSString *Meins; ///< Base Unit of Measure - Edm.String
@property (strong, nonatomic) NSDecimalNumber *Netwr; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSString *Waers; ///< Currency - Edm.String
@property (strong, nonatomic) NSDecimalNumber *AylikTahsil; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSString *KampanyaAdet; ///< Dummy - Edm.String
@property (strong, nonatomic) NSDecimalNumber *KampanyaliTutar; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *NetwrUsd; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *NetwrEur; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *NetwrGbp; ///< Net Value - Edm.Decimal

#pragma mark Static Methods
/**
 Static method that returns an array of EXPT_EKPLISTV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_EKPLISTV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_EKPLISTV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseEXPT_EKPLISTEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_EKPLISTV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_EKPLISTV0 entities.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_EKPLISTV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedEXPT_EKPLISTEntriesWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_EKPLISTV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a EXPT_EKPLISTV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_EKPLISTV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_EKPLISTV0 *)parseEXPT_EKPLISTEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_EKPLISTV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a EXPT_EKPLISTV0 entity.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_EKPLISTV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_EKPLISTV0 *)parseExpandedEXPT_EKPLISTEntryWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_EKPLISTV0 objects from a given array of ODataEntry objects.
 @param sdmEntries Array of ODataEntry objects.
 @return Array of EXPT_EKPLISTV0 objects.
*/
+ (NSMutableArray *)createEXPT_EKPLISTEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ZGARENTA_EKHIZMET_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(ODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ZGARENTA_EKHIZMET_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(ODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end

#pragma mark - EXPT_EKSURUCUV0
@interface EXPT_EKSURUCUV0 : BaseEntityType 

@property (strong, nonatomic) NSString *Malzeme; ///< Material - Edm.String
@property (strong, nonatomic) NSString *Maktx; ///< Material Description - Edm.String
@property (strong, nonatomic) NSDecimalNumber *Tutar; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *AylikTahsil; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSString *MaxAdet; ///< MAX_ADET - Edm.String
@property (strong, nonatomic) NSString *ParaBirimi; ///< Document Currency - Edm.String
@property (strong, nonatomic) NSString *Navigasyon; ///< Checkbox - Edm.String
@property (strong, nonatomic) NSString *BebekKoltugu; ///< Checkbox - Edm.String
@property (strong, nonatomic) NSString *EkSurucuSinirsiz; ///< Checkbox - Edm.String
@property (strong, nonatomic) NSString *MalzemeInfo; ///< Char255 - Edm.String
@property (strong, nonatomic) NSString *KampanyaAdet; ///< Dummy - Edm.String
@property (strong, nonatomic) NSDecimalNumber *KampanyaliTutar; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *TutarUsd; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *TutarEur; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *TutarGbp; ///< Net Value - Edm.Decimal

#pragma mark Static Methods
/**
 Static method that returns an array of EXPT_EKSURUCUV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_EKSURUCUV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_EKSURUCUV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseEXPT_EKSURUCUEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_EKSURUCUV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_EKSURUCUV0 entities.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_EKSURUCUV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedEXPT_EKSURUCUEntriesWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_EKSURUCUV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a EXPT_EKSURUCUV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_EKSURUCUV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_EKSURUCUV0 *)parseEXPT_EKSURUCUEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_EKSURUCUV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a EXPT_EKSURUCUV0 entity.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_EKSURUCUV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_EKSURUCUV0 *)parseExpandedEXPT_EKSURUCUEntryWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_EKSURUCUV0 objects from a given array of ODataEntry objects.
 @param sdmEntries Array of ODataEntry objects.
 @return Array of EXPT_EKSURUCUV0 objects.
*/
+ (NSMutableArray *)createEXPT_EKSURUCUEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ZGARENTA_EKHIZMET_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(ODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ZGARENTA_EKHIZMET_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(ODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end

#pragma mark - EXPT_HASARV0
@interface EXPT_HASARV0 : BaseEntityType 

@property (strong, nonatomic) NSDecimalNumber *TutarGbp; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *TutarEur; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *TutarUsd; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *KampanyaliTutar; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSString *KampanyaAdet; ///< Dummy - Edm.String
@property (strong, nonatomic) NSString *MalzemeInfo; ///< Char255 - Edm.String
@property (strong, nonatomic) NSString *Malzeme; ///< Material - Edm.String
@property (strong, nonatomic) NSString *EkSurucuSinirsiz; ///< Checkbox - Edm.String
@property (strong, nonatomic) NSString *Maktx; ///< Material Description - Edm.String
@property (strong, nonatomic) NSDecimalNumber *Tutar; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *AylikTahsil; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSString *BebekKoltugu; ///< Checkbox - Edm.String
@property (strong, nonatomic) NSString *MaxAdet; ///< MAX_ADET - Edm.String
@property (strong, nonatomic) NSString *ParaBirimi; ///< Document Currency - Edm.String
@property (strong, nonatomic) NSString *Navigasyon; ///< Checkbox - Edm.String

#pragma mark Static Methods
/**
 Static method that returns an array of EXPT_HASARV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_HASARV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_HASARV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseEXPT_HASAREntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_HASARV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_HASARV0 entities.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_HASARV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedEXPT_HASAREntriesWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_HASARV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a EXPT_HASARV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_HASARV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_HASARV0 *)parseEXPT_HASAREntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_HASARV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a EXPT_HASARV0 entity.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_HASARV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_HASARV0 *)parseExpandedEXPT_HASAREntryWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_HASARV0 objects from a given array of ODataEntry objects.
 @param sdmEntries Array of ODataEntry objects.
 @return Array of EXPT_HASARV0 objects.
*/
+ (NSMutableArray *)createEXPT_HASAREntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ZGARENTA_EKHIZMET_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(ODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ZGARENTA_EKHIZMET_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(ODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end

#pragma mark - EXPT_HIZMETV0
@interface EXPT_HIZMETV0 : BaseEntityType 

@property (strong, nonatomic) NSDecimalNumber *TutarGbp; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *TutarEur; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *TutarUsd; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *KampanyaliTutar; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSString *KampanyaAdet; ///< Dummy - Edm.String
@property (strong, nonatomic) NSString *MalzemeInfo; ///< Char255 - Edm.String
@property (strong, nonatomic) NSString *EkSurucuSinirsiz; ///< Checkbox - Edm.String
@property (strong, nonatomic) NSString *BebekKoltugu; ///< Checkbox - Edm.String
@property (strong, nonatomic) NSString *Navigasyon; ///< Checkbox - Edm.String
@property (strong, nonatomic) NSString *ParaBirimi; ///< Document Currency - Edm.String
@property (strong, nonatomic) NSString *MaxAdet; ///< MAX_ADET - Edm.String
@property (strong, nonatomic) NSDecimalNumber *AylikTahsil; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *Tutar; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSString *Maktx; ///< Material Description - Edm.String
@property (strong, nonatomic) NSString *Malzeme; ///< Material - Edm.String

#pragma mark Static Methods
/**
 Static method that returns an array of EXPT_HIZMETV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_HIZMETV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_HIZMETV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseEXPT_HIZMETEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_HIZMETV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_HIZMETV0 entities.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_HIZMETV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedEXPT_HIZMETEntriesWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_HIZMETV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a EXPT_HIZMETV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_HIZMETV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_HIZMETV0 *)parseEXPT_HIZMETEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_HIZMETV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a EXPT_HIZMETV0 entity.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_HIZMETV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_HIZMETV0 *)parseExpandedEXPT_HIZMETEntryWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_HIZMETV0 objects from a given array of ODataEntry objects.
 @param sdmEntries Array of ODataEntry objects.
 @return Array of EXPT_HIZMETV0 objects.
*/
+ (NSMutableArray *)createEXPT_HIZMETEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ZGARENTA_EKHIZMET_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(ODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ZGARENTA_EKHIZMET_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(ODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end

#pragma mark - EXPT_SIGORTAV0
@interface EXPT_SIGORTAV0 : BaseEntityType 

@property (strong, nonatomic) NSString *MaxAdet; ///< MAX_ADET - Edm.String
@property (strong, nonatomic) NSDecimalNumber *AylikTahsil; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *Tutar; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSString *Maktx; ///< Material Description - Edm.String
@property (strong, nonatomic) NSString *Malzeme; ///< Material - Edm.String
@property (strong, nonatomic) NSString *ParaBirimi; ///< Document Currency - Edm.String
@property (strong, nonatomic) NSString *Navigasyon; ///< Checkbox - Edm.String
@property (strong, nonatomic) NSString *BebekKoltugu; ///< Checkbox - Edm.String
@property (strong, nonatomic) NSString *EkSurucuSinirsiz; ///< Checkbox - Edm.String
@property (strong, nonatomic) NSString *MalzemeInfo; ///< Char255 - Edm.String
@property (strong, nonatomic) NSString *KampanyaAdet; ///< Dummy - Edm.String
@property (strong, nonatomic) NSDecimalNumber *KampanyaliTutar; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *TutarUsd; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *TutarEur; ///< Net Value - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *TutarGbp; ///< Net Value - Edm.Decimal

#pragma mark Static Methods
/**
 Static method that returns an array of EXPT_SIGORTAV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_SIGORTAV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_SIGORTAV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseEXPT_SIGORTAEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_SIGORTAV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_SIGORTAV0 entities.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_SIGORTAV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedEXPT_SIGORTAEntriesWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_SIGORTAV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a EXPT_SIGORTAV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_SIGORTAV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_SIGORTAV0 *)parseEXPT_SIGORTAEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_SIGORTAV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a EXPT_SIGORTAV0 entity.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_SIGORTAV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_SIGORTAV0 *)parseExpandedEXPT_SIGORTAEntryWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_SIGORTAV0 objects from a given array of ODataEntry objects.
 @param sdmEntries Array of ODataEntry objects.
 @return Array of EXPT_SIGORTAV0 objects.
*/
+ (NSMutableArray *)createEXPT_SIGORTAEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ZGARENTA_EKHIZMET_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(ODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ZGARENTA_EKHIZMET_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(ODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end



#pragma mark - ZGARENTA_EKHIZMET_SRVV0 Service Proxy
@interface ZGARENTA_EKHIZMET_SRVServiceV0 : BaseServiceObject

#pragma mark Query properties for service Entity Sets
/**
The OData query for the AdditionalEquipmentService collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *AdditionalEquipmentServiceSetQuery;

/**
The OData query for the EXPT_EKPLIST collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *EXPT_EKPLISTSetQuery;

/**
The OData query for the EXPT_EKSURUCU collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *EXPT_EKSURUCUSetQuery;

/**
The OData query for the EXPT_HASAR collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *EXPT_HASARSetQuery;

/**
The OData query for the EXPT_HIZMET collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *EXPT_HIZMETSetQuery;

/**
The OData query for the EXPT_SIGORTA collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *EXPT_SIGORTASetQuery;


#pragma mark Service Entity Set methods
/**
 Returns a collection of AdditionalEquipmentServiceV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of AdditionalEquipmentServiceV0 entities.
*/
- (NSMutableArray *)getAdditionalEquipmentServiceSetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific AdditionalEquipmentServiceV0 entity.
 @param ImppBegda Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.DateTime).
 @param ImppBeguz Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppDsube Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppEndda Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.DateTime).
 @param ImppEnduz Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppFikod Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppGrpkod Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppKampid Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppLangu Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppMarkaid Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppModelid Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppMsube Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppRezno Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppSozno Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getAdditionalEquipmentServiceSetEntryQueryWithImppBegda:(NSString *)ImppBegda andImppBeguz:(NSString *)ImppBeguz andImppDsube:(NSString *)ImppDsube andImppEndda:(NSString *)ImppEndda andImppEnduz:(NSString *)ImppEnduz andImppFikod:(NSString *)ImppFikod andImppGrpkod:(NSString *)ImppGrpkod andImppKampid:(NSString *)ImppKampid andImppLangu:(NSString *)ImppLangu andImppMarkaid:(NSString *)ImppMarkaid andImppModelid:(NSString *)ImppModelid andImppMsube:(NSString *)ImppMsube andImppRezno:(NSString *)ImppRezno andImppSozno:(NSString *)ImppSozno;

/**
 Returns the OData query for a specific AdditionalEquipmentServiceV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param ImppBegda Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.DateTime).
 @param ImppBeguz Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppDsube Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppEndda Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.DateTime).
 @param ImppEnduz Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppFikod Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppGrpkod Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppKampid Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppLangu Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppMarkaid Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppModelid Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppMsube Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppRezno Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @param ImppSozno Part of the AdditionalEquipmentServiceV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getAdditionalEquipmentServiceSetEntryQueryTypedWithImppBegda:(NSDate *)ImppBegda andImppBeguz:(NSString *)ImppBeguz andImppDsube:(NSString *)ImppDsube andImppEndda:(NSDate *)ImppEndda andImppEnduz:(NSString *)ImppEnduz andImppFikod:(NSString *)ImppFikod andImppGrpkod:(NSString *)ImppGrpkod andImppKampid:(NSString *)ImppKampid andImppLangu:(NSString *)ImppLangu andImppMarkaid:(NSString *)ImppMarkaid andImppModelid:(NSString *)ImppModelid andImppMsube:(NSString *)ImppMsube andImppRezno:(NSString *)ImppRezno andImppSozno:(NSString *)ImppSozno;

/**
 Returns a specific AdditionalEquipmentServiceV0 entity from the provided data.
 @param aData The NSData containing the AdditionalEquipmentServiceV0 information to be parsed to a AdditionalEquipmentServiceV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a AdditionalEquipmentServiceV0 entity. Returns nil if the data in invalid.
*/
- (AdditionalEquipmentServiceV0 *)getAdditionalEquipmentServiceSetEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of EXPT_EKPLISTV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_EKPLISTV0 entities.
*/
- (NSMutableArray *)getEXPT_EKPLISTSetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific EXPT_EKPLISTV0 entity.
 @param Msube Part of the EXPT_EKPLISTV0 unique identifier (of type Edm.String).
 @param Matnr Part of the EXPT_EKPLISTV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_EKPLISTSetEntryQueryWithMsube:(NSString *)Msube andMatnr:(NSString *)Matnr;

/**
 Returns the OData query for a specific EXPT_EKPLISTV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param Msube Part of the EXPT_EKPLISTV0 unique identifier (of type Edm.String).
 @param Matnr Part of the EXPT_EKPLISTV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_EKPLISTSetEntryQueryTypedWithMsube:(NSString *)Msube andMatnr:(NSString *)Matnr;

/**
 Returns a specific EXPT_EKPLISTV0 entity from the provided data.
 @param aData The NSData containing the EXPT_EKPLISTV0 information to be parsed to a EXPT_EKPLISTV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_EKPLISTV0 entity. Returns nil if the data in invalid.
*/
- (EXPT_EKPLISTV0 *)getEXPT_EKPLISTSetEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of EXPT_EKSURUCUV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_EKSURUCUV0 entities.
*/
- (NSMutableArray *)getEXPT_EKSURUCUSetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific EXPT_EKSURUCUV0 entity.
 @param Malzeme Part of the EXPT_EKSURUCUV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_EKSURUCUSetEntryQueryWithMalzeme:(NSString *)Malzeme;

/**
 Returns the OData query for a specific EXPT_EKSURUCUV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param Malzeme Part of the EXPT_EKSURUCUV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_EKSURUCUSetEntryQueryTypedWithMalzeme:(NSString *)Malzeme;

/**
 Returns a specific EXPT_EKSURUCUV0 entity from the provided data.
 @param aData The NSData containing the EXPT_EKSURUCUV0 information to be parsed to a EXPT_EKSURUCUV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_EKSURUCUV0 entity. Returns nil if the data in invalid.
*/
- (EXPT_EKSURUCUV0 *)getEXPT_EKSURUCUSetEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of EXPT_HASARV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_HASARV0 entities.
*/
- (NSMutableArray *)getEXPT_HASARSetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific EXPT_HASARV0 entity.
 @param Malzeme Part of the EXPT_HASARV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_HASARSetEntryQueryWithMalzeme:(NSString *)Malzeme;

/**
 Returns the OData query for a specific EXPT_HASARV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param Malzeme Part of the EXPT_HASARV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_HASARSetEntryQueryTypedWithMalzeme:(NSString *)Malzeme;

/**
 Returns a specific EXPT_HASARV0 entity from the provided data.
 @param aData The NSData containing the EXPT_HASARV0 information to be parsed to a EXPT_HASARV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_HASARV0 entity. Returns nil if the data in invalid.
*/
- (EXPT_HASARV0 *)getEXPT_HASARSetEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of EXPT_HIZMETV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_HIZMETV0 entities.
*/
- (NSMutableArray *)getEXPT_HIZMETSetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific EXPT_HIZMETV0 entity.
 @param Malzeme Part of the EXPT_HIZMETV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_HIZMETSetEntryQueryWithMalzeme:(NSString *)Malzeme;

/**
 Returns the OData query for a specific EXPT_HIZMETV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param Malzeme Part of the EXPT_HIZMETV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_HIZMETSetEntryQueryTypedWithMalzeme:(NSString *)Malzeme;

/**
 Returns a specific EXPT_HIZMETV0 entity from the provided data.
 @param aData The NSData containing the EXPT_HIZMETV0 information to be parsed to a EXPT_HIZMETV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_HIZMETV0 entity. Returns nil if the data in invalid.
*/
- (EXPT_HIZMETV0 *)getEXPT_HIZMETSetEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of EXPT_SIGORTAV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_SIGORTAV0 entities.
*/
- (NSMutableArray *)getEXPT_SIGORTASetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific EXPT_SIGORTAV0 entity.
 @param Malzeme Part of the EXPT_SIGORTAV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_SIGORTASetEntryQueryWithMalzeme:(NSString *)Malzeme;

/**
 Returns the OData query for a specific EXPT_SIGORTAV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param Malzeme Part of the EXPT_SIGORTAV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_SIGORTASetEntryQueryTypedWithMalzeme:(NSString *)Malzeme;

/**
 Returns a specific EXPT_SIGORTAV0 entity from the provided data.
 @param aData The NSData containing the EXPT_SIGORTAV0 information to be parsed to a EXPT_SIGORTAV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_SIGORTAV0 entity. Returns nil if the data in invalid.
*/
- (EXPT_SIGORTAV0 *)getEXPT_SIGORTASetEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


#pragma mark Service Function Import methods
@end