/*
 
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1
 
 File: ZGARENTA_versiyon_srvServiceDeclarations.h
 Abstract: Aliases for the generated proxy class names of the ZGARENTA_versiyon_srv service.
   
*/

#import <Foundation/Foundation.h>
#import "ZGARENTA_versiyon_srvServiceV0.h"

@compatibility_alias ZGARENTA_versiyon_srvService ZGARENTA_versiyon_srvServiceV0;
@compatibility_alias VersiyonService VersiyonServiceV0;
