/*
 
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1
 
 File: ZGARENTA_ARAC_SRVServiceDeclarations.h
 Abstract: Aliases for the generated proxy class names of the ZGARENTA_ARAC_SRV service.
   
*/

#import <Foundation/Foundation.h>
#import "ZGARENTA_ARAC_SRVServiceV0.h"

@compatibility_alias ZGARENTA_ARAC_SRVService ZGARENTA_ARAC_SRVServiceV0;
@compatibility_alias AvailCarService AvailCarServiceV0;
@compatibility_alias ET_ARACLISTE ET_ARACLISTEV0;
@compatibility_alias ET_EXPIRY ET_EXPIRYV0;
@compatibility_alias ET_FIYAT ET_FIYATV0;
@compatibility_alias ET_INDIRIMLIST ET_INDIRIMLISTV0;
@compatibility_alias ET_KAMPANYA ET_KAMPANYAV0;
@compatibility_alias ET_RESERV ET_RESERVV0;
@compatibility_alias IMPT_MSUBE IMPT_MSUBEV0;
