/*
 
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1
 
 File: ZGARENTA_EKHIZMET_SRVServiceDeclarations.h
 Abstract: Aliases for the generated proxy class names of the ZGARENTA_EKHIZMET_SRV service.
   
*/

#import <Foundation/Foundation.h>
#import "ZGARENTA_EKHIZMET_SRVServiceV0.h"

@compatibility_alias ZGARENTA_EKHIZMET_SRVService ZGARENTA_EKHIZMET_SRVServiceV0;
@compatibility_alias AdditionalEquipmentService AdditionalEquipmentServiceV0;
@compatibility_alias EXPT_EKPLIST EXPT_EKPLISTV0;
@compatibility_alias EXPT_EKSURUCU EXPT_EKSURUCUV0;
@compatibility_alias EXPT_HASAR EXPT_HASARV0;
@compatibility_alias EXPT_HIZMET EXPT_HIZMETV0;
@compatibility_alias EXPT_SIGORTA EXPT_SIGORTAV0;
