/*
 
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1
 
 File: ZGARENTA_GET_CUST_KK_SRVServiceDeclarations.h
 Abstract: Aliases for the generated proxy class names of the ZGARENTA_GET_CUST_KK_SRV service.
   
*/

#import <Foundation/Foundation.h>
#import "ZGARENTA_GET_CUST_KK_SRVServiceV0.h"

@compatibility_alias ZGARENTA_GET_CUST_KK_SRVService ZGARENTA_GET_CUST_KK_SRVServiceV0;
@compatibility_alias CustKKService CustKKServiceV0;
@compatibility_alias ET_CARDS ET_CARDSV0;
