/*
 
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1
 
 File: ZGARENTA_versiyon_srvServiceV0.h
 Abstract: The generated proxy classes for the ZGARENTA_versiyon_srv Service.   
*/

#import <Foundation/Foundation.h>
#import "BaseEntityType.h"
#import "BaseComplexType.h"
#import "BaseServiceObject.h"

#pragma mark - Complex Types



#pragma mark - Entity Types

/**
 Each of the following classes represents an entity-type of the ZGARENTA_versiyon_srvServiceV0 service.
 
 Any entity-type class should be used as following:
 
 1. The entity object may represent an existing entry of an appropriate service collection,
 if the object is initialized using data returned from an appropriate service call.
 This may be achieved by using the initWithSDMEntry: constructor,
 or using the static methods creating the entity object (parse<entity-type-name>EntriesWithData,
 parse<entity-type-name>EntryWithData, and create<entity-type-name>EntriesForSDMEntries).
 
 For retrieving the entry data, use the appropriate query properties and methods of this class 
 and of the ZGARENTA_versiyon_srvServiceV0 class, and then execute the request (see the SDMConnectivityHelper class).
 
 2. Another option is to use this entity object as a new entry to create in an appropriate service collection.
 In this case, use the init constructor and set the appropriate properties. 
 Note that some features (as navigation properties) are not available in this mode (since it is not yet an actual service entry).
 Use the SDMConnectivityHelper class and the getXMLForCreateRequest method of the BaseServiceObject class, to send the 'create' request.
 Then use the service response for constructing a new object, in order to represent the entry as existed in the service. 
 
 In both operation modes, setting the entity property values will not affect the service until the changes are sent to the server.
 For sending changes to the server, see the SDMConnectivityHelper class and the getXMLForRequest methods of the BaseServiceObject class.
 It is recommended to use the server response for constructing a new object, in order to represent the entry as existed in the service.
 
 Note: For proper behavior of this class, make sure to initialize the ZGARENTA_versiyon_srvServiceV0 class
 in your application, before initializing the entity-type class objects.
*/
 

#pragma mark - VersiyonServiceV0
@interface VersiyonServiceV0 : BaseEntityType 

@property (strong, nonatomic) NSString *IAppName; ///< Character Field Length = 10 - Edm.String
@property (strong, nonatomic) NSString *IVers; ///< 3-Byte field - Edm.String
@property (strong, nonatomic) NSString *EReturn; ///< Single-Character Indicator - Edm.String
@property (strong, nonatomic) NSString *ELink; ///< Character 300 - Edm.String

#pragma mark Static Methods
/**
 Static method that returns an array of VersiyonServiceV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to VersiyonServiceV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of VersiyonServiceV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseVersiyonServiceEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of VersiyonServiceV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to VersiyonServiceV0 entities.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of VersiyonServiceV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedVersiyonServiceEntriesWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single VersiyonServiceV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a VersiyonServiceV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a VersiyonServiceV0 entity. Returns nil if the data in invalid.
*/
+ (VersiyonServiceV0 *)parseVersiyonServiceEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single VersiyonServiceV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a VersiyonServiceV0 entity.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a VersiyonServiceV0 entity. Returns nil if the data in invalid.
*/
+ (VersiyonServiceV0 *)parseExpandedVersiyonServiceEntryWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of VersiyonServiceV0 objects from a given array of ODataEntry objects.
 @param sdmEntries Array of ODataEntry objects.
 @return Array of VersiyonServiceV0 objects.
*/
+ (NSMutableArray *)createVersiyonServiceEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ZGARENTA_versiyon_srvServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(ODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ZGARENTA_versiyon_srvServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(ODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end



#pragma mark - ZGARENTA_versiyon_srvV0 Service Proxy
@interface ZGARENTA_versiyon_srvServiceV0 : BaseServiceObject

#pragma mark Query properties for service Entity Sets
/**
The OData query for the VersiyonService collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *VersiyonServiceQuery;


#pragma mark Service Entity Set methods
/**
 Returns a collection of VersiyonServiceV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of VersiyonServiceV0 entities.
*/
- (NSMutableArray *)getVersiyonServiceWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific VersiyonServiceV0 entity.
 @param IAppName Part of the VersiyonServiceV0 unique identifier (of type Edm.String).
 @param IVers Part of the VersiyonServiceV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getVersiyonServiceEntryQueryWithIAppName:(NSString *)IAppName andIVers:(NSString *)IVers;

/**
 Returns the OData query for a specific VersiyonServiceV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param IAppName Part of the VersiyonServiceV0 unique identifier (of type Edm.String).
 @param IVers Part of the VersiyonServiceV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getVersiyonServiceEntryQueryTypedWithIAppName:(NSString *)IAppName andIVers:(NSString *)IVers;

/**
 Returns a specific VersiyonServiceV0 entity from the provided data.
 @param aData The NSData containing the VersiyonServiceV0 information to be parsed to a VersiyonServiceV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a VersiyonServiceV0 entity. Returns nil if the data in invalid.
*/
- (VersiyonServiceV0 *)getVersiyonServiceEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


#pragma mark Service Function Import methods
@end