/*
 
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1
 
 File: ZGARENTA_REZERVASYON_SRVServiceDeclarations.h
 Abstract: Aliases for the generated proxy class names of the ZGARENTA_REZERVASYON_SRV service.
   
*/

#import <Foundation/Foundation.h>
#import "ZGARENTA_REZERVASYON_SRVServiceV0.h"

@compatibility_alias ZGARENTA_REZERVASYON_SRVService ZGARENTA_REZERVASYON_SRVServiceV0;
@compatibility_alias EsOutput EsOutputV0;
@compatibility_alias IsInput IsInputV0;
@compatibility_alias IsUserinfo IsUserinfoV0;
@compatibility_alias ET_KK_RETURN ET_KK_RETURNV0;
@compatibility_alias ET_RETURN ET_RETURNV0;
@compatibility_alias IT_ARACLAR IT_ARACLARV0;
@compatibility_alias IT_EKSURUCU IT_EKSURUCUV0;
@compatibility_alias IT_FATURA_ADRES IT_FATURA_ADRESV0;
@compatibility_alias IT_ITEMS IT_ITEMSV0;
@compatibility_alias IT_SDREZERV IT_SDREZERVV0;
@compatibility_alias IT_TAHSILAT IT_TAHSILATV0;
@compatibility_alias ReservationService ReservationServiceV0;
