/*
 
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1
 
 File: ZGARENTA_OFIS_SRVServiceDeclarations.h
 Abstract: Aliases for the generated proxy class names of the ZGARENTA_OFIS_SRV service.
   
*/

#import <Foundation/Foundation.h>
#import "ZGARENTA_OFIS_SRVServiceV0.h"

@compatibility_alias ZGARENTA_OFIS_SRVService ZGARENTA_OFIS_SRVServiceV0;
@compatibility_alias EXPT_CALISMA_ZAMANI EXPT_CALISMA_ZAMANIV0;
@compatibility_alias EXPT_SUBE_BILGILERI EXPT_SUBE_BILGILERIV0;
@compatibility_alias EXPT_TATIL_ZAMANI EXPT_TATIL_ZAMANIV0;
@compatibility_alias OfficeService OfficeServiceV0;
