/*
 
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1
 
 File: ZGARENTA_OFIS_SRVServiceV0.h
 Abstract: The generated proxy classes for the ZGARENTA_OFIS_SRV Service.   
*/

#import <Foundation/Foundation.h>
#import "BaseEntityType.h"
#import "BaseComplexType.h"
#import "BaseServiceObject.h"

#pragma mark - Complex Types



#pragma mark - Entity Types

/**
 Each of the following classes represents an entity-type of the ZGARENTA_OFIS_SRVServiceV0 service.
 
 Any entity-type class should be used as following:
 
 1. The entity object may represent an existing entry of an appropriate service collection,
 if the object is initialized using data returned from an appropriate service call.
 This may be achieved by using the initWithSDMEntry: constructor,
 or using the static methods creating the entity object (parse<entity-type-name>EntriesWithData,
 parse<entity-type-name>EntryWithData, and create<entity-type-name>EntriesForSDMEntries).
 
 For retrieving the entry data, use the appropriate query properties and methods of this class 
 and of the ZGARENTA_OFIS_SRVServiceV0 class, and then execute the request (see the SDMConnectivityHelper class).
 
 2. Another option is to use this entity object as a new entry to create in an appropriate service collection.
 In this case, use the init constructor and set the appropriate properties. 
 Note that some features (as navigation properties) are not available in this mode (since it is not yet an actual service entry).
 Use the SDMConnectivityHelper class and the getXMLForCreateRequest method of the BaseServiceObject class, to send the 'create' request.
 Then use the service response for constructing a new object, in order to represent the entry as existed in the service. 
 
 In both operation modes, setting the entity property values will not affect the service until the changes are sent to the server.
 For sending changes to the server, see the SDMConnectivityHelper class and the getXMLForRequest methods of the BaseServiceObject class.
 It is recommended to use the server response for constructing a new object, in order to represent the entry as existed in the service.
 
 Note: For proper behavior of this class, make sure to initialize the ZGARENTA_OFIS_SRVServiceV0 class
 in your application, before initializing the entity-type class objects.
*/
 

#pragma mark - EXPT_CALISMA_ZAMANIV0
@interface EXPT_CALISMA_ZAMANIV0 : BaseEntityType 

@property (strong, nonatomic) ODataDuration *Endti; ///< End time - Edm.Time
@property (strong, nonatomic) ODataDuration *Begti; ///< Start time - Edm.Time
@property (strong, nonatomic) NSString *Cadaytx; ///< Text, 40 Characters Long - Edm.String
@property (strong, nonatomic) NSString *Caday; ///< CADAY - Edm.String
@property (strong, nonatomic) NSString *AltSube; ///< ALT_SUBE - Edm.String
@property (strong, nonatomic) NSString *MerkezSube; ///< Storage Location - Edm.String

#pragma mark Static Methods
/**
 Static method that returns an array of EXPT_CALISMA_ZAMANIV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_CALISMA_ZAMANIV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_CALISMA_ZAMANIV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseEXPT_CALISMA_ZAMANIEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_CALISMA_ZAMANIV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_CALISMA_ZAMANIV0 entities.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_CALISMA_ZAMANIV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedEXPT_CALISMA_ZAMANIEntriesWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_CALISMA_ZAMANIV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a EXPT_CALISMA_ZAMANIV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_CALISMA_ZAMANIV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_CALISMA_ZAMANIV0 *)parseEXPT_CALISMA_ZAMANIEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_CALISMA_ZAMANIV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a EXPT_CALISMA_ZAMANIV0 entity.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_CALISMA_ZAMANIV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_CALISMA_ZAMANIV0 *)parseExpandedEXPT_CALISMA_ZAMANIEntryWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_CALISMA_ZAMANIV0 objects from a given array of ODataEntry objects.
 @param sdmEntries Array of ODataEntry objects.
 @return Array of EXPT_CALISMA_ZAMANIV0 objects.
*/
+ (NSMutableArray *)createEXPT_CALISMA_ZAMANIEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ZGARENTA_OFIS_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(ODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ZGARENTA_OFIS_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(ODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end

#pragma mark - EXPT_SUBE_BILGILERIV0
@interface EXPT_SUBE_BILGILERIV0 : BaseEntityType 

@property (strong, nonatomic) NSString *Aktifsube; ///< AKTIFSUBE - Edm.String
@property (strong, nonatomic) NSString *Ceptel; ///< CEPTEL - Edm.String
@property (strong, nonatomic) NSString *Email; ///< EMAIL - Edm.String
@property (strong, nonatomic) NSString *Fax; ///< Telefax - Edm.String
@property (strong, nonatomic) NSString *Tel; ///< Telephone 1 - Edm.String
@property (strong, nonatomic) NSString *Adres; ///< ADRES - Edm.String
@property (strong, nonatomic) NSString *Ykord; ///< Longitude - Edm.String
@property (strong, nonatomic) NSString *Xkord; ///< Latitude - Edm.String
@property (strong, nonatomic) NSString *Kostltx; ///< Description - Edm.String
@property (strong, nonatomic) NSString *Kostl; ///< Cost Center - Edm.String
@property (strong, nonatomic) NSString *Gsbertx; ///< Business area description - Edm.String
@property (strong, nonatomic) NSString *Gsber; ///< Business Area - Edm.String
@property (strong, nonatomic) NSString *Sehirtx; ///< Text, 40 Characters Long - Edm.String
@property (strong, nonatomic) NSString *Sehir; ///< SEHIR - Edm.String
@property (strong, nonatomic) NSString *Bolgetx; ///< Text, 40 Characters Long - Edm.String
@property (strong, nonatomic) NSString *Bolge; ///< BOLGE - Edm.String
@property (strong, nonatomic) NSString *AltSubetiptx; ///< Text, 40 Characters Long - Edm.String
@property (strong, nonatomic) NSString *AltSubetip; ///< ALT_SUBETIP - Edm.String
@property (strong, nonatomic) NSString *AltSubetx; ///< ALT_SUBETX - Edm.String
@property (strong, nonatomic) NSString *AltSube; ///< ALT_SUBE - Edm.String
@property (strong, nonatomic) NSString *MerkezSubetx; ///< Descr. of Storage Loc. - Edm.String
@property (strong, nonatomic) NSString *MerkezSube; ///< Storage Location - Edm.String

#pragma mark Static Methods
/**
 Static method that returns an array of EXPT_SUBE_BILGILERIV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_SUBE_BILGILERIV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_SUBE_BILGILERIV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseEXPT_SUBE_BILGILERIEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_SUBE_BILGILERIV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_SUBE_BILGILERIV0 entities.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_SUBE_BILGILERIV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedEXPT_SUBE_BILGILERIEntriesWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_SUBE_BILGILERIV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a EXPT_SUBE_BILGILERIV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_SUBE_BILGILERIV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_SUBE_BILGILERIV0 *)parseEXPT_SUBE_BILGILERIEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_SUBE_BILGILERIV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a EXPT_SUBE_BILGILERIV0 entity.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_SUBE_BILGILERIV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_SUBE_BILGILERIV0 *)parseExpandedEXPT_SUBE_BILGILERIEntryWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_SUBE_BILGILERIV0 objects from a given array of ODataEntry objects.
 @param sdmEntries Array of ODataEntry objects.
 @return Array of EXPT_SUBE_BILGILERIV0 objects.
*/
+ (NSMutableArray *)createEXPT_SUBE_BILGILERIEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ZGARENTA_OFIS_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(ODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ZGARENTA_OFIS_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(ODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end

#pragma mark - EXPT_TATIL_ZAMANIV0
@interface EXPT_TATIL_ZAMANIV0 : BaseEntityType 

@property (strong, nonatomic) ODataDuration *Endti; ///< End time - Edm.Time
@property (strong, nonatomic) ODataDuration *Begti; ///< Start time - Edm.Time
@property (strong, nonatomic) NSDate *Begda; ///< Start Date - Edm.DateTime
@property (strong, nonatomic) NSString *AltSube; ///< ALT_SUBE - Edm.String
@property (strong, nonatomic) NSString *MerkezSube; ///< Storage Location - Edm.String

#pragma mark Static Methods
/**
 Static method that returns an array of EXPT_TATIL_ZAMANIV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_TATIL_ZAMANIV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_TATIL_ZAMANIV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseEXPT_TATIL_ZAMANIEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_TATIL_ZAMANIV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to EXPT_TATIL_ZAMANIV0 entities.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_TATIL_ZAMANIV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedEXPT_TATIL_ZAMANIEntriesWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_TATIL_ZAMANIV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a EXPT_TATIL_ZAMANIV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_TATIL_ZAMANIV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_TATIL_ZAMANIV0 *)parseEXPT_TATIL_ZAMANIEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single EXPT_TATIL_ZAMANIV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a EXPT_TATIL_ZAMANIV0 entity.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_TATIL_ZAMANIV0 entity. Returns nil if the data in invalid.
*/
+ (EXPT_TATIL_ZAMANIV0 *)parseExpandedEXPT_TATIL_ZAMANIEntryWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of EXPT_TATIL_ZAMANIV0 objects from a given array of ODataEntry objects.
 @param sdmEntries Array of ODataEntry objects.
 @return Array of EXPT_TATIL_ZAMANIV0 objects.
*/
+ (NSMutableArray *)createEXPT_TATIL_ZAMANIEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ZGARENTA_OFIS_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(ODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ZGARENTA_OFIS_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(ODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end

#pragma mark - OfficeServiceV0
@interface OfficeServiceV0 : BaseEntityType 

@property (strong, nonatomic) NSString *Message; ///< Message text - Edm.String
@property (strong, nonatomic) NSString *Type; ///< Message type - Edm.String
@property (strong, nonatomic) NSString *ImppMerkezSube; ///< Storage Location - Edm.String
@property (strong, nonatomic) NSString *ImppBolge; ///< IMPP_BOLGE - Edm.String
@property (strong, nonatomic) NSString *ImppAltSube; ///< IMPP_ALT_SUBE - Edm.String
#pragma mark Entity Navigation Properties
@property (strong, nonatomic) ODataQuery *EXPT_TATIL_ZAMANISetQuery;
@property (strong, nonatomic) NSMutableArray *EXPT_TATIL_ZAMANISet;
@property (strong, nonatomic) ODataQuery *EXPT_SUBE_BILGILERISetQuery;
@property (strong, nonatomic) NSMutableArray *EXPT_SUBE_BILGILERISet;
@property (strong, nonatomic) ODataQuery *EXPT_CALISMA_ZAMANISetQuery;
@property (strong, nonatomic) NSMutableArray *EXPT_CALISMA_ZAMANISet;

#pragma mark Static Methods
/**
 Static method that returns an array of OfficeServiceV0 entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to OfficeServiceV0 entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of OfficeServiceV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseOfficeServiceEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of OfficeServiceV0 entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to OfficeServiceV0 entities.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of OfficeServiceV0 entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedOfficeServiceEntriesWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single OfficeServiceV0 entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a OfficeServiceV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a OfficeServiceV0 entity. Returns nil if the data in invalid.
*/
+ (OfficeServiceV0 *)parseOfficeServiceEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single OfficeServiceV0 entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a OfficeServiceV0 entity.
 @param aServiceDocument The ODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a OfficeServiceV0 entity. Returns nil if the data in invalid.
*/
+ (OfficeServiceV0 *)parseExpandedOfficeServiceEntryWithData:(NSData *)aData andServiceDocument:(ODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of OfficeServiceV0 objects from a given array of ODataEntry objects.
 @param sdmEntries Array of ODataEntry objects.
 @return Array of OfficeServiceV0 objects.
*/
+ (NSMutableArray *)createOfficeServiceEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ZGARENTA_OFIS_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(ODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ZGARENTA_OFIS_SRVServiceV0 class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(ODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;


#pragma mark Entity Navigation Property loading methods
/**
 Navigation property. Loads EXPT_TATIL_ZAMANISet details for this entity from the provided data.
 @param aData The NSData containing the EXPT_TATIL_ZAMANISet information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadEXPT_TATIL_ZAMANISetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Navigation property. Loads EXPT_SUBE_BILGILERISet details for this entity from the provided data.
 @param aData The NSData containing the EXPT_SUBE_BILGILERISet information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadEXPT_SUBE_BILGILERISetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Navigation property. Loads EXPT_CALISMA_ZAMANISet details for this entity from the provided data.
 @param aData The NSData containing the EXPT_CALISMA_ZAMANISet information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadEXPT_CALISMA_ZAMANISetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


@end



#pragma mark - ZGARENTA_OFIS_SRVV0 Service Proxy
@interface ZGARENTA_OFIS_SRVServiceV0 : BaseServiceObject

#pragma mark Query properties for service Entity Sets
/**
The OData query for the EXPT_CALISMA_ZAMANI collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *EXPT_CALISMA_ZAMANISetQuery;

/**
The OData query for the EXPT_SUBE_BILGILERI collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *EXPT_SUBE_BILGILERISetQuery;

/**
The OData query for the EXPT_TATIL_ZAMANI collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *EXPT_TATIL_ZAMANISetQuery;

/**
The OData query for the OfficeService collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *OfficeServiceSetQuery;


#pragma mark Service Entity Set methods
/**
 Returns a collection of EXPT_CALISMA_ZAMANIV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_CALISMA_ZAMANIV0 entities.
*/
- (NSMutableArray *)getEXPT_CALISMA_ZAMANISetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific EXPT_CALISMA_ZAMANIV0 entity.
 @param Endti Part of the EXPT_CALISMA_ZAMANIV0 unique identifier (of type Edm.Time).
 @param Begti Part of the EXPT_CALISMA_ZAMANIV0 unique identifier (of type Edm.Time).
 @param Cadaytx Part of the EXPT_CALISMA_ZAMANIV0 unique identifier (of type Edm.String).
 @param Caday Part of the EXPT_CALISMA_ZAMANIV0 unique identifier (of type Edm.String).
 @param AltSube Part of the EXPT_CALISMA_ZAMANIV0 unique identifier (of type Edm.String).
 @param MerkezSube Part of the EXPT_CALISMA_ZAMANIV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_CALISMA_ZAMANISetEntryQueryWithEndti:(NSString *)Endti andBegti:(NSString *)Begti andCadaytx:(NSString *)Cadaytx andCaday:(NSString *)Caday andAltSube:(NSString *)AltSube andMerkezSube:(NSString *)MerkezSube;

/**
 Returns the OData query for a specific EXPT_CALISMA_ZAMANIV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param Endti Part of the EXPT_CALISMA_ZAMANIV0 unique identifier (of type Edm.Time).
 @param Begti Part of the EXPT_CALISMA_ZAMANIV0 unique identifier (of type Edm.Time).
 @param Cadaytx Part of the EXPT_CALISMA_ZAMANIV0 unique identifier (of type Edm.String).
 @param Caday Part of the EXPT_CALISMA_ZAMANIV0 unique identifier (of type Edm.String).
 @param AltSube Part of the EXPT_CALISMA_ZAMANIV0 unique identifier (of type Edm.String).
 @param MerkezSube Part of the EXPT_CALISMA_ZAMANIV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_CALISMA_ZAMANISetEntryQueryTypedWithEndti:(ODataDuration *)Endti andBegti:(ODataDuration *)Begti andCadaytx:(NSString *)Cadaytx andCaday:(NSString *)Caday andAltSube:(NSString *)AltSube andMerkezSube:(NSString *)MerkezSube;

/**
 Returns a specific EXPT_CALISMA_ZAMANIV0 entity from the provided data.
 @param aData The NSData containing the EXPT_CALISMA_ZAMANIV0 information to be parsed to a EXPT_CALISMA_ZAMANIV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_CALISMA_ZAMANIV0 entity. Returns nil if the data in invalid.
*/
- (EXPT_CALISMA_ZAMANIV0 *)getEXPT_CALISMA_ZAMANISetEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of EXPT_SUBE_BILGILERIV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_SUBE_BILGILERIV0 entities.
*/
- (NSMutableArray *)getEXPT_SUBE_BILGILERISetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific EXPT_SUBE_BILGILERIV0 entity.
 @param Ceptel Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Email Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Fax Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Tel Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Adres Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Ykord Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Xkord Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Kostltx Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Kostl Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Gsbertx Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Gsber Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Sehirtx Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Sehir Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Bolgetx Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Bolge Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param AltSubetiptx Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param AltSubetip Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param AltSubetx Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param AltSube Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param MerkezSubetx Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param MerkezSube Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_SUBE_BILGILERISetEntryQueryWithCeptel:(NSString *)Ceptel andEmail:(NSString *)Email andFax:(NSString *)Fax andTel:(NSString *)Tel andAdres:(NSString *)Adres andYkord:(NSString *)Ykord andXkord:(NSString *)Xkord andKostltx:(NSString *)Kostltx andKostl:(NSString *)Kostl andGsbertx:(NSString *)Gsbertx andGsber:(NSString *)Gsber andSehirtx:(NSString *)Sehirtx andSehir:(NSString *)Sehir andBolgetx:(NSString *)Bolgetx andBolge:(NSString *)Bolge andAltSubetiptx:(NSString *)AltSubetiptx andAltSubetip:(NSString *)AltSubetip andAltSubetx:(NSString *)AltSubetx andAltSube:(NSString *)AltSube andMerkezSubetx:(NSString *)MerkezSubetx andMerkezSube:(NSString *)MerkezSube;

/**
 Returns the OData query for a specific EXPT_SUBE_BILGILERIV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param Ceptel Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Email Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Fax Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Tel Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Adres Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Ykord Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Xkord Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Kostltx Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Kostl Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Gsbertx Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Gsber Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Sehirtx Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Sehir Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Bolgetx Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param Bolge Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param AltSubetiptx Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param AltSubetip Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param AltSubetx Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param AltSube Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param MerkezSubetx Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @param MerkezSube Part of the EXPT_SUBE_BILGILERIV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_SUBE_BILGILERISetEntryQueryTypedWithCeptel:(NSString *)Ceptel andEmail:(NSString *)Email andFax:(NSString *)Fax andTel:(NSString *)Tel andAdres:(NSString *)Adres andYkord:(NSString *)Ykord andXkord:(NSString *)Xkord andKostltx:(NSString *)Kostltx andKostl:(NSString *)Kostl andGsbertx:(NSString *)Gsbertx andGsber:(NSString *)Gsber andSehirtx:(NSString *)Sehirtx andSehir:(NSString *)Sehir andBolgetx:(NSString *)Bolgetx andBolge:(NSString *)Bolge andAltSubetiptx:(NSString *)AltSubetiptx andAltSubetip:(NSString *)AltSubetip andAltSubetx:(NSString *)AltSubetx andAltSube:(NSString *)AltSube andMerkezSubetx:(NSString *)MerkezSubetx andMerkezSube:(NSString *)MerkezSube;

/**
 Returns a specific EXPT_SUBE_BILGILERIV0 entity from the provided data.
 @param aData The NSData containing the EXPT_SUBE_BILGILERIV0 information to be parsed to a EXPT_SUBE_BILGILERIV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_SUBE_BILGILERIV0 entity. Returns nil if the data in invalid.
*/
- (EXPT_SUBE_BILGILERIV0 *)getEXPT_SUBE_BILGILERISetEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of EXPT_TATIL_ZAMANIV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of EXPT_TATIL_ZAMANIV0 entities.
*/
- (NSMutableArray *)getEXPT_TATIL_ZAMANISetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific EXPT_TATIL_ZAMANIV0 entity.
 @param Endti Part of the EXPT_TATIL_ZAMANIV0 unique identifier (of type Edm.Time).
 @param Begti Part of the EXPT_TATIL_ZAMANIV0 unique identifier (of type Edm.Time).
 @param Begda Part of the EXPT_TATIL_ZAMANIV0 unique identifier (of type Edm.DateTime).
 @param AltSube Part of the EXPT_TATIL_ZAMANIV0 unique identifier (of type Edm.String).
 @param MerkezSube Part of the EXPT_TATIL_ZAMANIV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_TATIL_ZAMANISetEntryQueryWithEndti:(NSString *)Endti andBegti:(NSString *)Begti andBegda:(NSString *)Begda andAltSube:(NSString *)AltSube andMerkezSube:(NSString *)MerkezSube;

/**
 Returns the OData query for a specific EXPT_TATIL_ZAMANIV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param Endti Part of the EXPT_TATIL_ZAMANIV0 unique identifier (of type Edm.Time).
 @param Begti Part of the EXPT_TATIL_ZAMANIV0 unique identifier (of type Edm.Time).
 @param Begda Part of the EXPT_TATIL_ZAMANIV0 unique identifier (of type Edm.DateTime).
 @param AltSube Part of the EXPT_TATIL_ZAMANIV0 unique identifier (of type Edm.String).
 @param MerkezSube Part of the EXPT_TATIL_ZAMANIV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getEXPT_TATIL_ZAMANISetEntryQueryTypedWithEndti:(ODataDuration *)Endti andBegti:(ODataDuration *)Begti andBegda:(NSDate *)Begda andAltSube:(NSString *)AltSube andMerkezSube:(NSString *)MerkezSube;

/**
 Returns a specific EXPT_TATIL_ZAMANIV0 entity from the provided data.
 @param aData The NSData containing the EXPT_TATIL_ZAMANIV0 information to be parsed to a EXPT_TATIL_ZAMANIV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a EXPT_TATIL_ZAMANIV0 entity. Returns nil if the data in invalid.
*/
- (EXPT_TATIL_ZAMANIV0 *)getEXPT_TATIL_ZAMANISetEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of OfficeServiceV0 entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of OfficeServiceV0 entities.
*/
- (NSMutableArray *)getOfficeServiceSetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific OfficeServiceV0 entity.
 @param ImppMerkezSube Part of the OfficeServiceV0 unique identifier (of type Edm.String).
 @param ImppBolge Part of the OfficeServiceV0 unique identifier (of type Edm.String).
 @param ImppAltSube Part of the OfficeServiceV0 unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getOfficeServiceSetEntryQueryWithImppMerkezSube:(NSString *)ImppMerkezSube andImppBolge:(NSString *)ImppBolge andImppAltSube:(NSString *)ImppAltSube;

/**
 Returns the OData query for a specific OfficeServiceV0 entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param ImppMerkezSube Part of the OfficeServiceV0 unique identifier (of type Edm.String).
 @param ImppBolge Part of the OfficeServiceV0 unique identifier (of type Edm.String).
 @param ImppAltSube Part of the OfficeServiceV0 unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getOfficeServiceSetEntryQueryTypedWithImppMerkezSube:(NSString *)ImppMerkezSube andImppBolge:(NSString *)ImppBolge andImppAltSube:(NSString *)ImppAltSube;

/**
 Returns a specific OfficeServiceV0 entity from the provided data.
 @param aData The NSData containing the OfficeServiceV0 information to be parsed to a OfficeServiceV0 entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a OfficeServiceV0 entity. Returns nil if the data in invalid.
*/
- (OfficeServiceV0 *)getOfficeServiceSetEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


#pragma mark Service Function Import methods
@end